import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/field_model.dart';

class AnalysisService {
  static final AnalysisService _instance = AnalysisService._internal();
  factory AnalysisService() => _instance;
  AnalysisService._internal();

  Future<Map<String, dynamic>?> analyzeField(Field field, {bool forceRefresh = false}) async {
    try {
      // The Python backend's firestore_listeners automatically populate an 'analysis' 
      // field inside the plot document whenever boundaries or crops change.
      // We no longer need local caching as Firestore handles offline persistence natively!
      
      final docSnap = await FirebaseFirestore.instance
          .collection('plots')
          .doc(field.id)
          .get();
          
      if (docSnap.exists && docSnap.data()!.containsKey('analysis')) {
        return docSnap.data()!['analysis'] as Map<String, dynamic>;
      } else {
        // The analysis hasn't been generated by backend yet, or doesn't exist.
        return null;
      }
    } catch (e) {
      print("Firestore error fetching analysis for field ${field.name}: $e");
      return null;
    }
  }
}
