// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpTva1e_g00oyhK0Kc8h_cGfarqH1Wk4',
    appId: '1:369768559517:web:a30d4c349e00f62beaf574',
    messagingSenderId: '369768559517',
    projectId: 'agrinetra-fjns-2026',
    authDomain: 'agrinetra-fjns-2026.firebaseapp.com',
    storageBucket: 'agrinetra-fjns-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC22o6CJC94xqtwxzoakqxaUvq-qSCdT0E',
    appId: '1:369768559517:android:174b0df648b557b9eaf574',
    messagingSenderId: '369768559517',
    projectId: 'agrinetra-fjns-2026',
    storageBucket: 'agrinetra-fjns-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOsIaOL9wGxDvRnRfty-nIWQ3zmxDojhc',
    appId: '1:369768559517:ios:ad80f523466460b8eaf574',
    messagingSenderId: '369768559517',
    projectId: 'agrinetra-fjns-2026',
    storageBucket: 'agrinetra-fjns-2026.firebasestorage.app',
    iosBundleId: 'com.example.agrinetra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOsIaOL9wGxDvRnRfty-nIWQ3zmxDojhc',
    appId: '1:369768559517:ios:ad80f523466460b8eaf574',
    messagingSenderId: '369768559517',
    projectId: 'agrinetra-fjns-2026',
    storageBucket: 'agrinetra-fjns-2026.firebasestorage.app',
    iosBundleId: 'com.example.agrinetra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIpTva1e_g00oyhK0Kc8h_cGfarqH1Wk4',
    appId: '1:369768559517:web:a27a8a87067cec4eeaf574',
    messagingSenderId: '369768559517',
    projectId: 'agrinetra-fjns-2026',
    authDomain: 'agrinetra-fjns-2026.firebaseapp.com',
    storageBucket: 'agrinetra-fjns-2026.firebasestorage.app',
  );
}
